name: Generate snake animation and update GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"  # Se ejecuta cada 12 horas
  workflow_dispatch:

  push:
    branches:
      - main  # Se activa cuando hay un push en "main"

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Crear directorio dist
        run: mkdir -p dist

      - name: Generar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Descargar estadísticas con Token
        run: |
          curl -o dist/github-stats.svg "https://github-readme-stats.vercel.app/api?username=LennyMA&theme=radical&show_icons=true&include_all_commits=true&hide=stars,issues&token=${{ secrets.STATS_TOKEN }}"

      - name: Subir archivos a GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
